= Mitmachen
Christoph Till
2023-02-01
:jbake-type: page
:jbake-status: published
:jbake-tags: page, asciidoc
:idprefix:


Mitmachen kann jeder, der bereits ein Blechblasinstrument spielt (oder gespielt hat und wieder einsteigen möchte) oder das Spielen neu erlernen möchte.
Angesprochen sind hierbei Kinder ab 8 Jahren, aber auch Erwachsene jeden Alters.
Bei Interesse wenden sie sich an den Chorleiter Michael Hitze
Für alle genannten Interessenten können individuelle Angebote gemäß der Vorkenntnisse gestaltet werden

Eine besondere Veranstaltung richtete der Posaunenchor zusammen mit dem Posaunenwerk der EKHN, Bezirke Starkenburg und Rhein-Main aus. Der Jugendposaunentag 2011 fand in der Halle Urberach statt. Erzählt wurde eine leicht abgewandelte Geschichte der Posaunen von Jericho, die die Mauern in unseren Herzen einreißen ließen. 150 Jung- und junggebliebene Bläser aus der Region testeten einen Tag lang, ob die Mauern der Halle Urberach eine größere Tragkraft als die Mauern von Jericho haben. Am Ende der Veranstaltung bescheinigten Dekan Tag und Bürgermeister Kern eine gelungene Veranstaltung und eine stabile Statik der Halle. Dennoch musste die Halle Urberach ein Jahr später von Grund auf saniert werden...


Bis heute tritt der Posaunenchor bei Veranstaltungen der Gemeinde wie Gottesdiensten in der Kirche und im Freien, bei Gemeindefesten, der Hirtenweihnacht etc. auf. Das städtische Leben außerhalb der Gemeinde bereichert der Chor durch Mitwirkung bei Veranstaltungen wie der städtischen Seniorenfeier, dem Nikolausmarkt und neuerdings auch dem Fastnachtsumzug. Entsprechend des breiten Auftrittsspektrums ist auch das Musikrepertoire vielfältig. Neben der klassischen Posaunenchorliteratur mit Choralbearbeitungen und alter Spielmusik sind heutzutage auch Swing, Jazz und Pop in vielen Posaunenchören zu hören. Heute besteht der Chor aus ca. 15 Mitgliedern, neue interessierte Musiker sind herzlich willkommen.

Heinz Held gründete im Jahre 1965 den Posaunenchor Urberach. Der erste Auftritt des Chores fand bei der Grundsteinlegung des ev. Gemeindehauses in der Baugrube statt. Unter den 8 Mitwirkenden waren damals unter anderem auch Dieter Wienesen und Walter Barlen, die dem Chor als Gründungsmitglieder über 40 Jahre angehörten.

In den Folgejahren wechselte die Besetzung häufiger, jedoch bildete sich eine Stammbesetzung heraus, die den Chor über Jahrzehnte hinaus getragen hat. Typische Einsätze des Chores waren auch früher schon Gottesdienstbegleitungen, Kurrende Blasen in der Adventszeit bzw. Nikolausmarkt, Mitwirkung bei der städtischen Seniorenfeier, Mitgestaltung des Gemeindefestes und seit den 1980er Jahren auch das jährliche Reformationskonzert. Hier ein Bild eines Gottesdienstes im Grünen aus dem Jahr 1975.

1976 schrieb der Kirchentag einen Wettbewerb aus, das Motto des Kirchentags \'einer trägt den anderen\' graphisch auszugestalten. Der Architekt, Künstler und damaliges Chormitglied Kurt Schlösser beteiligte sich an dem Wettbewerb und konnte den Platz 1 in Hessen und Nassau erreichen. Als Preis bekam er damals eine Trompete geschenkt, auf der seine Frau Anita Schlösser heute noch im Chor spielt. Sein Wettbewerbsbeitrag:

Heinz Held bildete auch einen großen Teil der heute noch aktiven Bläser des Chores auf ihrem Blechblasinstrument aus. Somit leistete der Posaunenchor auch einen Beitrag zur Jugendarbeit der Gemeinde. Das Gruppenbild aus 1984 zeigt, dass damals auch durchaus unter 20 jährige dem Chor angehörten.

Besonders beliebt bei den Chormitgliedern waren stets die jährlich im Herbst veranstalteten Posaunenchorfreizeiten. Diese wurden zum einen für intensive Probenarbeit genutzt, zum anderen nahmen auch die Familienmitglieder der Musikerinnen und Musiker an den Fahrten teil, so dass auch Freizeitaktivitäten nicht zu kurz kamen. Lange Wanderungen, Besuche von Sehenswürdigkeiten, Sportaktivitäten wie das beliebte Pausen-Tischtennis, Tierparkbesuche, Lagerfeuer etc. und natürlich das abendliche Befeuchten der ach so trockenen Bläserkehlen standen auf dem Programm. 

Eine besondere Chorfahrt war sicherlich der Besuch der Partnergemeinde Kirchohmfeld kurz nach der Maueröffnung im Jahre 1990. Dort gestaltete der Chor einige musikalische Einsätze (unter anderem die Einweihung einer Gedenkstätte mit dem damaligen thüringischen Innenminister und natürlich den Sonntags-Gottesdienst), und erlebte eine große Gastfreundschaft, eine schöne Gegend und viele interessante Eindrücke.

Im Jahre 2005 feierte der Chor in der Petruskirche sein 40 jähriges Bestehen mit einem Festgottesdienst, bei dem auch benachbarte Posaunenchöre der Region teilnahmen. Die 3 oben erwähnten Gründungsmitglieder Heinz Held (+2012), Dieter Wienesen (+2012) und Walter Barlen wurden durch den damaligen Vorsitzenden des Posaunenwerks (Bezirk Starkenburg), Gerhard Schröder für 40 Jahre Chorleitungs- bzw. Bläserdienst geehrt. Gruppenbild nach dem Festgottesdienst:

Nach dem Festgottesdienst fand im Gemeindehaus ein Empfang statt, bei dem zahlreiche Grußworte an den Chor gerichtet wurden und einige phantasievolle Geschenke überreicht wurden. Als Ehrengäste konnten neben dem damaligen Pfarrer F. Decker die früheren Pfarrer Marx und Müller begrüßt werden.

Im Jahre 2007 erfolgte der Stabwechsel: Michael Hitzel übernimmt die Chorleitung von Chorgründer Heinz Held und leitet seitdem den Posaunenchor bis heute. Heinz Held blieb dem Chor noch einige Jahre als aktiver Musiker erhalten. Landesposaunenwart Frank Vogel, bei dem Michael Hitzel seine Ausbildung zur Chorleitung abschloss, überbrachte selbst zum Wechsel der musikalischen Leitung Glückwünsche und musizierte im Gottesdienst fleißig mit.

Eine besondere Veranstaltung richtete der Posaunenchor zusammen mit dem Posaunenwerk der EKHN, Bezirke Starkenburg und Rhein-Main aus. Der Jugendposaunentag 2011 fand in der Halle Urberach statt. Erzählt wurde eine leicht abgewandelte Geschichte der Posaunen von Jericho, die die Mauern in unseren Herzen einreißen ließen. 150 Jung- und junggebliebene Bläser aus der Region testeten einen Tag lang, ob die Mauern der Halle Urberach eine größere Tragkraft als die Mauern von Jericho haben. Am Ende der Veranstaltung bescheinigten Dekan Tag und Bürgermeister Kern eine gelungene Veranstaltung und eine stabile Statik der Halle. Dennoch musste die Halle Urberach ein Jahr später von Grund auf saniert werden...

Bis heute tritt der Posaunenchor bei Veranstaltungen der Gemeinde wie Gottesdiensten in der Kirche und im Freien, bei Gemeindefesten, der Hirtenweihnacht etc. auf. Das städtische Leben außerhalb der Gemeinde bereichert der Chor durch Mitwirkung bei Veranstaltungen wie der städtischen Seniorenfeier, dem Nikolausmarkt und neuerdings auch dem Fastnachtsumzug. Entsprechend des breiten Auftrittsspektrums ist auch das Musikrepertoire vielfältig. Neben der klassischen Posaunenchorliteratur mit Choralbearbeitungen und alter Spielmusik sind heutzutage auch Swing, Jazz und Pop in vielen Posaunenchören zu hören. Heute besteht der Chor aus ca. 15 Mitgliedern, neue interessierte Musiker sind herzlich willkommen.

'Geschichte des Posaunenchores'


In den Folgejahren wechselte die Besetzung häufiger, jedoch bildete sich eine Stammbesetzung heraus, die den Chor über Jahrzehnte hinaus getragen hat. Typische Einsätze des Chores waren auch früher schon Gottesdienstbegleitungen, Kurrende Blasen in der Adventszeit bzw. Nikolausmarkt, Mitwirkung bei der städtischen Seniorenfeier, Mitgestaltung des Gemeindefestes und seit den 1980er Jahren auch das jährliche Reformationskonzert. Hier ein Bild eines Gottesdienstes im Grünen aus dem Jahr 1975.

1976 schrieb der Kirchentag einen Wettbewerb aus, das Motto des Kirchentags \'einer trägt den anderen\' graphisch auszugestalten. Der Architekt, Künstler und damaliges Chormitglied Kurt Schlösser beteiligte sich an dem Wettbewerb und konnte den Platz 1 in Hessen und Nassau erreichen. Als Preis bekam er damals eine Trompete geschenkt, auf der seine Frau Anita Schlösser heute noch im Chor spielt. Sein Wettbewerbsbeitrag:

Heinz Held bildete auch einen großen Teil der heute noch aktiven Bläser des Chores auf ihrem Blechblasinstrument aus. Somit leistete der Posaunenchor auch einen Beitrag zur Jugendarbeit der Gemeinde. Das Gruppenbild aus 1984 zeigt, dass damals auch durchaus unter 20 jährige dem Chor angehörten.

Besonders beliebt bei den Chormitgliedern waren stets die jährlich im Herbst veranstalteten Posaunenchorfreizeiten. Diese wurden zum einen für intensive Probenarbeit genutzt, zum anderen nahmen auch die Familienmitglieder der Musikerinnen und Musiker an den Fahrten teil, so dass auch Freizeitaktivitäten nicht zu kurz kamen. Lange Wanderungen, Besuche von Sehenswürdigkeiten, Sportaktivitäten wie das beliebte Pausen-Tischtennis, Tierparkbesuche, Lagerfeuer etc. und natürlich das abendliche Befeuchten der ach so trockenen Bläserkehlen standen auf dem Programm. </span></p>\n<p class=\"Normal_Web_\"><span class=\"tm9\">Eine besondere Chorfahrt war sicherlich der Besuch der Partnergemeinde Kirchohmfeld kurz nach der Maueröffnung im Jahre 1990. Dort gestaltete der Chor einige musikalische Einsätze (unter anderem die Einweihung einer Gedenkstätte mit dem damaligen thüringischen Innenminister und natürlich den Sonntags-Gottesdienst), und erlebte eine große Gastfreundschaft, eine schöne Gegend und viele interessante Eindrücke.

Im Jahre 2005 feierte der Chor in der Petruskirche sein 40 jähriges Bestehen mit einem Festgottesdienst, bei dem auch benachbarte Posaunenchöre der Region teilnahmen. Die 3 oben erwähnten Gründungsmitglieder Heinz Held (+2012), Dieter Wienesen (+2012) und Walter Barlen wurden durch den damaligen Vorsitzenden des Posaunenwerks (Bezirk Starkenburg), Gerhard Schröder für 40 Jahre Chorleitungs- bzw. Bläserdienst geehrt. Gruppenbild nach dem Festgottesdienst:

Nach dem Festgottesdienst fand im Gemeindehaus ein Empfang statt, bei dem zahlreiche Grußworte an den Chor gerichtet wurden und einige phantasievolle Geschenke überreicht wurden. Als Ehrengäste konnten neben dem damaligen Pfarrer F. Decker die früheren Pfarrer Marx und Müller begrüßt werden.

Bis heute tritt der Posaunenchor bei Veranstaltungen der Gemeinde wie Gottesdiensten in der Kirche und im Freien, bei Gemeindefesten, der Hirtenweihnacht etc. auf. Das städtische Leben außerhalb der Gemeinde bereichert der Chor durch Mitwirkung bei Veranstaltungen wie der städtischen Seniorenfeier, dem Nikolausmarkt und neuerdings auch dem Fastnachtsumzug. Entsprechend des breiten Auftrittsspektrums ist auch das Musikrepertoire vielfältig. Neben der klassischen Posaunenchorliteratur mit Choralbearbeitungen und alter Spielmusik sind heutzutage auch Swing, Jazz und Pop in vielen Posaunenchören zu hören. Heute besteht der Chor aus ca. 15 Mitgliedern, neue interessierte Musiker sind herzlich willkommen.

Nach dem Festgottesdienst fand im Gemeindehaus ein Empfang statt, bei dem zahlreiche Grußworte an den Chor gerichtet wurden und einige phantasievolle Geschenke überreicht wurden. Als Ehrengäste konnten neben dem damaligen Pfarrer F. Decker die früheren Pfarrer Marx und Müller begrüßt werden.

Bis heute tritt der Posaunenchor bei Veranstaltungen der Gemeinde wie Gottesdiensten in der Kirche und im Freien, bei Gemeindefesten, der Hirtenweihnacht etc. auf. Das städtische Leben außerhalb der Gemeinde bereichert der Chor durch Mitwirkung bei Veranstaltungen wie der städtischen Seniorenfeier, dem Nikolausmarkt und neuerdings auch dem Fastnachtsumzug. Entsprechend des breiten Auftrittsspektrums ist auch das Musikrepertoire vielfältig. Neben der klassischen Posaunenchorliteratur mit Choralbearbeitungen und alter Spielmusik sind heutzutage auch Swing, Jazz und Pop in vielen Posaunenchören zu hören. Heute besteht der Chor aus ca. 15 Mitgliedern, neue interessierte Musiker sind herzlich willkommen

In den Folgejahren wechselte die Besetzung häufiger, jedoch bildete sich eine Stammbesetzung heraus, die den Chor über Jahrzehnte hinaus getragen hat. Typische Einsätze des Chores waren auch früher schon Gottesdienstbegleitungen, Kurrende Blasen in der Adventszeit bzw. Nikolausmarkt, Mitwirkung bei der städtischen Seniorenfeier, Mitgestaltung des Gemeindefestes und seit den 1980er Jahren auch das jährliche Reformationskonzert. Hier ein Bild eines Gottesdienstes im Grünen aus dem Jahr 1975.

1976 schrieb der Kirchentag einen Wettbewerb aus, das Motto des Kirchentags \'einer trägt den anderen\' graphisch auszugestalten. Der Architekt, Künstler und damaliges Chormitglied Kurt Schlösser beteiligte sich an dem Wettbewerb und konnte den Platz 1 in Hessen und Nassau erreichen. Als Preis bekam er damals eine Trompete geschenkt, auf der seine Frau Anita Schlösser heute noch im Chor spielt. Sein Wettbewerbsbeitrag:

Bis heute tritt der Posaunenchor bei Veranstaltungen der Gemeinde wie Gottesdiensten in der Kirche und im Freien, bei Gemeindefesten, der Hirtenweihnacht etc. auf. Das städtische Leben außerhalb der Gemeinde bereichert der Chor durch Mitwirkung bei Veranstaltungen wie der städtischen Seniorenfeier, dem Nikolausmarkt und neuerdings auch dem Fastnachtsumzug. Entsprechend des breiten Auftrittsspektrums ist auch das Musikrepertoire vielfältig. Neben der klassischen Posaunenchorliteratur mit Choralbearbeitungen und alter Spielmusik sind heutzutage auch Swing, Jazz und Pop in vielen Posaunenchören zu hören. Heute besteht der Chor aus ca. 15 Mitgliedern, neue interessierte Musiker sind herzlich willkommen.

Der Posaunenchor im Jahre 2016:

Geschichte des Posaunenchores
Im Jahre 2015: 50 Jahre Musik für die Kirche


Der Urberacher Posaunenchor feiert Geburtstag</span></p>\r\n<p class=\"Normal tm6\"><span class=\"tm7\">Heinz Held gründete im Jahre 1965 den Posaunenchor Urberach. Der erste Auftritt des Chores fand bei der Grundsteinlegung des ev. Gemeindehauses in der Baugrube statt. Unter den 8 Mitwirkenden waren damals unter anderem auch Dieter Wienesen und Walter Barlen, die dem Chor als Gründungsmitglieder über 40 Jahre angehörten.

In den Folgejahren wechselte die Besetzung häufiger, jedoch bildete sich eine Stammbesetzung heraus, die den Chor über Jahrzehnte hinaus getragen hat. Typische Einsätze des Chores waren auch früher schon Gottesdienstbegleitungen, Kurrende Blasen in der Adventszeit bzw. Nikolausmarkt, Mitwirkung bei der städtischen Seniorenfeier, Mitgestaltung des Gemeindefestes und seit den 1980er Jahren auch das jährliche Reformationskonzert. Hier ein Bild eines Gottesdienstes im Grünen aus dem Jahr 1975.



1976 schrieb der Kirchentag einen Wettbewerb aus, das Motto des Kirchentags \'einer trägt den anderen\' graphisch auszugestalten. Der Architekt, Künstler und damaliges Chormitglied Kurt Schlösser beteiligte sich an dem Wettbewerb und konnte den Platz 1 in Hessen und Nassau erreichen. Als Preis bekam er damals eine Trompete geschenkt, auf der seine Frau Anita Schlösser heute noch im Chor spielt. Sein Wettbewerbsbeitrag:</


Heinz Held bildete auch einen großen Teil der heute noch aktiven Bläser des Chores auf ihrem Blechblasinstrument aus. Somit leistete der Posaunenchor auch einen Beitrag zur Jugendarbeit der Gemeinde. Das Gruppenbild aus 1984 zeigt, dass damals auch durchaus unter 20 jährige dem Chor angehörten.


Besonders beliebt bei den Chormitgliedern waren stets die jährlich im Herbst veranstalteten Posaunenchorfreizeiten. Diese wurden zum einen für intensive Probenarbeit genutzt, zum anderen nahmen auch die Familienmitglieder der Musikerinnen und Musiker an den Fahrten teil, so dass auch Freizeitaktivitäten nicht zu kurz kamen. Lange Wanderungen, Besuche von Sehenswürdigkeiten, Sportaktivitäten wie das beliebte Pausen-Tischtennis, Tierparkbesuche, Lagerfeuer etc. und natürlich das abendliche Befeuchten der ach so trockenen Bläserkehlen standen auf dem Programm. </span></p>\r\n<p class=\"Normal_Web_\"><span class=\"tm9\">Eine besondere Chorfahrt war sicherlich der Besuch der Partnergemeinde Kirchohmfeld kurz nach der Maueröffnung im Jahre 1990. Dort gestaltete der Chor einige musikalische Einsätze (unter anderem die Einweihung einer Gedenkstätte mit dem damaligen thüringischen Innenminister und natürlich den Sonntags-Gottesdienst), und erlebte eine große Gastfreundschaft, eine schöne Gegend und viele interessante Eindrücke.


Im Jahre 2005 feierte der Chor in der Petruskirche sein 40 jähriges Bestehen mit einem Festgottesdienst, bei dem auch benachbarte Posaunenchöre der Region teilnahmen. Die 3 oben erwähnten Gründungsmitglieder Heinz Held (+2012), Dieter Wienesen (+2012) und Walter Barlen wurden durch das heutige Chormitglied und damaligen Vorsitzenden des Posaunenwerks (Bezirk Starkenburg), Gerhard Schröder für 40 Jahre Chorleitungs- bzw. Bläserdienst geehrt. Gruppenbild nach dem Festgottesdienst:</span></p>\r\n<p class=\"Normal_Web_\" 
Nach dem Festgottesdienst fand im Gemeindehaus ein Empfang statt, bei dem zahlreiche Grußworte an den Chor gerichtet wurden und einige phantasievolle Geschenke überreicht wurden. Als Ehrengäste konnten neben dem damaligen Pfarrer F. Decker die früheren Pfarrer Marx und Müller begrüßt werden. 


Im Jahre 2007 erfolgte der Stabwechsel: Michael Hitzel übernimmt die Chorleitung von Chorgründer Heinz Held und leitet seitdem den Posaunenchor bis heute. Heinz Held blieb dem Chor noch einige Jahre als aktiver Musiker erhalten. Landesposaunenwart Frank Vogel, bei dem Michael Hitzel seine Ausbildung zur Chorleitung abschloss, überbrachte selbst zum Wechsel der musikalischen Leitung Glückwünsche und musizierte im Gottesdienst fleißig mit.

Das Programm wird diesem Anlass gemäß einige besinnliche Stücke beinhalten, dennoch wird der Posaunenchor auch in diesem Jahr wieder eine große Bandbreite der Literatur für Bläserchöre vorstellen. So werden auch neue geistliche Lieder sowie Arrangements im Swing und Pop Stil den Kontrapunkt im Programmablauf setzen. Ein Höhepunkt wird die Vertonung des Reformationschorals \'Ein feste Burg ist unser Gott\' von Bernd Geiersbach sein, der Text des Liedes wird hierin eindringlich mit musikalischen Mitteln dargestellt. Das mittlerweile obligatorische Abendlied wird natürlich auch nicht fehlen.</span></p>\r\n<p class=\"Normal\"><span style=\"font-size: 10pt;\">Der Posaunenchor freut sich auf zahlreiche Besucher des ca. einstündigen Konzerts. Der Eintritt ist frei, um Spenden wird gebeten.

Von der Kuppel der Frauenkirche riefen acht Bläserinnen und Bläser des Urberacher Posaunenchores mit Trompeten und Posaunen die Dresdner Protestanten zum Gottesdienst am Sonntag, den 3. Mai 2015 in ihr Gotteshaus. Bei herrlichem Sonnenschein spielten sie von der Laterne auf der prächtigen Kuppel Choräle zum Sonntag Kantate. Anschließend genossen die Urberacher Bläser beim musikalischen Gottesdienst den Klang der Orgel, gespielt vom Frauenkirchenorganist Samuel Kummer, Chor und Solisten der Frauenkirche mit Mozarts Krönungsmesse und die Predigt des Pfarrers der Frauenkirche Holger Treutmann . Dieses Ereignis war für den Posaunenchor ein erster Höhepunkt im Jubiläumsjahr 2015.